### ISSUE TITLE
Upgrade to nginx-ingress-controller 0.29.x (or current latest)

### ISSUE THREAD

**Issue by tobiasmcnulty** [caktus/ansible-role-k8s-web-cluster#3]
It looks like there's a new version available that we should probably upgrade to: https://kubernetes.github.io/ingress-nginx/deploy/

**Comment by copelco** [comment]
Also incorporate potential improvements from @dpoirier :

> It looks as if we've modified the other two yaml files, but if we haven't modified mandatory.yaml, we could install from the source URL and not need our own copy (and make it clear we're using it unmodified). Here's how I'm doing that in another project that is using all three files unmodified:

```
 # https://kubernetes.github.io/ingress-nginx/deploy/
    k8s:
      definition: "{{ lookup('url', item, split_lines=False) }}"
      state: present
      wait: yes
      validate:
        fail_on_error: yes
        strict: yes
    with_items:
    - https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.29.0/deploy/static/mandatory.yaml
    - https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.29.0/deploy/static/provider/aws/service-l4.yaml
    - https://raw.githubusercontent.com/kubernetes/ingress-nginx/nginx-0.29.0/deploy/static/provider/aws/patch-configmap-l4.yaml
```
